package com.shahbytes.chathub.domain.type;

public enum EventType {
    MESSAGE_CREATED,
    MESSAGE_SENT,

    CONVERSATION_CREATED,
    CONVERSATION_UPDATED,
    CONVERSATION_REMOVED,

    CONVERSATION_MEMBER_ADDED,
    CONVERSATION_MEMBER_REMOVED,

    CONVERSATION_DELETED,
    CONVERSATION_DELETED_FOR_USER,

    TYPING_STARTED,
    TYPING_STOPPED,

    USER_BLOCKED,
    USER_UNBLOCKED,

    TEST
}
